name: playnime
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.3 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:

dependencies:
  ansicolor: ^2.0.1
  faker: ^2.0.0
  html: ^0.15.0
  http: ^0.13.4
